### PR TITLE
TLS options doesn't work with custom agent in Node.js < 0.12

### LINKED ISSUE #86: Pass option `rejectUnauthorized ` to https module

### LINKED ISSUE #119: TLS options doesn't work with custom agent in Node.js < 0.12
~~~js
var myRootCA = require('fs').readFileSync('myRootCA.pem');
var opts = { 
  protocol: 'https:', 
  port: 443, 
  ca: myRootCA, 
  agent: { name: 'api', maxSockets: 80 },
  /* ··· */
};
~~~

~~~js
// node.js 0.12+

require('asker')(opts, function(err, res) { console.error(err) })
// > null

// node.js 0.10

require('asker')(opts, function(err, res) { console.error(err) })
// > Error: SELF_SIGNED_CERT_IN_CHAIN

delete opt.agent;
require('asker')(opts, function(err, res) { console.error(err) })
// > null
~~~

### PR DESCRIPTION
**Pull request by narqo**
~~**WIP!** Waiting for tests!~~

- fix #119
- closes #86

Node.js<0.12 [creates a new Agent][1] for https request if **tls options** are passed.

If user specifies her custom agent (or agent properties in our case), this agent should deal with TLS options by itself.

This patch is only necessary for Node.js=0.10 but should not affect modern versions.

~~~js
› ~/.local/opt/node-v0.10/bin/node -e "require('./')({ protocol:'https:', /*···*/ ca: require('fs').readFileSync('./MyInternalRootCA.pem') }, function(err, res) { console.error(err); console.log(res ? res.statusCode : '?') })"
null
200

› ~/.local/opt/node-v0.12/bin/node -e "require('./')({ protocol:'https:', /*···*/ ca: require('fs').readFileSync('./MyInternalRootCA.pem') }, function(err, res) { console.error(err); console.log(res ? res.statusCode : '?') })"
null
200

› ~/.local/opt/node-v4/bin/node -e "require('./')({ protocol:'https:', /*···*/ ca: require('fs').readFileSync('./MyInternalRootCA.pem') }, function(err, res) { console.error(err); console.log(res ? res.statusCode : '?') })"
null
200

› ~/.local/opt/node-v0.10/bin/node -e "require('./')({ protocol:'https:', /*···*/ rejectUnauthorized: false }, function(err, res) { console.error(err); console.log(res ? res.statusCode : '?') })"
null
200
~~~

[1]: https://github.com/nodejs/node/blob/v0.10.40/lib/https.js#L109-L121

### CODE REVIEW

File: lib/asker.js [hunk 1]
```diff
@@ -246,6 +246,41 @@ Request.prototype._processOptions = function(options) {
...
 };
 
+Request.prototype._createAgent = function(agentOpts) {
+    var options = this.options,
+        defaultOpts = {
+            name: undefined,
+            protocol: options.protocol
+        };
+
+    // @note we have to pass TLS options to Agent explicitly because Node.js<0.12 doesn't do it
```
Comment (narqo) [inline lib/asker.js]: This options can't be used if `defaultOpts`, as `Object.assign` copy all enumerable keys even if they are `undefined`. In this case it may lead to unwanted sideeffects.

**Comment by narqo** [comment]
:dancer:

**Comment by Flackus** [comment]
:8ball:
